openapi: 3.0.0
info:
  title: students API
  contact: {}
  version: "1.0"
servers:
  - url: https://students-api-sonali.onrender.com/api/v1
    variables: {}
paths:
  /students:
    get:
      tags:
        - Students
      summary: Get All Students
      operationId: GetAllStudents
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    post:
      tags:
        - Students
      summary: Create Student
      operationId: CreateStudent
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreateStudentRequest"
                - example:
                    SchoolName: Russell Branchs School
                    Grade: grade 1
            example:
              SchoolName: Russell Branchs School
              Grade: grade 1
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /students/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The student ID
    get:
      tags:
        - Students
      summary: Get Single Student
      operationId: GetSingleStudent
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Students
      summary: Update Student Info
      operationId: UpdateStudentInfo
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/UpdateStudentInfoRequest"
                - example:
                    SchoolName: Russell Ranch Elementary School
            example:
              SchoolName: Russell Ranch Elementary School
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []

    delete:
      tags:
        - Students
      summary: Delete Student Record
      operationId: DeleteStudentRecord
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/RegisterUserRequest"
                - example:
                    name: Veda
                    email: Veda@gmail.com
                    password: secret123
            example:
              name: Veda
              email: Veda@gmail.com
              password: secret123
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/LoginUserRequest"
                - example:
                    email: Veda@gmail.com
                    password: secret123
            example:
              email: Veda@gmail.com
              password: secret123
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Veda
        email: Veda@gmail.com
        password: secret123
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: Veda@gmail.com
        password: secret123
    UpdateStudentInfoRequest:
      title: UpdateStudentInfoRequest
      required:
        - SchoolName
      type: object
      properties:
        SchoolName:
          type: string
      example:
        SchoolName: Russell Ranch Elementary School
    CreateStudentRequest:
      title: CreateStudentRequest
      required:
        - SchoolName
        - Grade
      type: object
      properties:
        SchoolName:
          type: string
        Grade:
          type: string
      example:
        SchoolName: Russell Branchs School
        Grade: grade 1
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Students
    description: ""
  - name: Auth
    description: ""
